language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/Konstantin8105/cs
  - go get github.com/Konstantin8105/pow
script:
  - go test -covermode=count -coverprofile=coverage.out ./... -v
  - $GOPATH/bin/goveralls    -coverprofile=coverage.out -service=travis-ci
